name: Update AKS Release files
on:
  schedule:
    - cron: '0 * * * *' # runs every hour at 00 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Run Golang program
        run: go run main.go
      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Updating AKS Release Status"
            git push
          else
            echo "Nothing changed"
          fi
